portfolio/config/routes.rb
Rails.application.routes.draw do
 
 
  get 'pages/home'  
  root 'pages#home'
   get 'portfolio'       =>'pages#portfolio'
   get 'blog'            =>'pages#blog'
   get 'contact'         =>'pages#contact'
  

end

portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

portfolio/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
   def contact
   end
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/pages_helper.rb
module PagesHelper
end

portfolio/app/helpers/users_helper.rb
module UsersHelper
end

portfolio/app/views/layouts/_header.html.erb
<header>
    <!-- Introduction -->
               <section id="home" name="home">
       <div id="header">
         <div class="container">
           <div class="row">
             
             <h1>Bienvenue sur mon portfolio !</h1>
               
               <br>

               <br>
             <div class="col-lg-12">
             </div>
           </div>
         </div>
       </div>
   </section>
  


    <!-- Navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

<a class="navbar-brand" href="home">Medina-Virginie</a>
        </div>
        <div class="navbar-collapse collapse">
<ul class="nav navbar-nav navbar-right">


      <ul>
        <li><%= link_to'home', root_url%></li>
        <li><%= link_to'portfolio', portfolio_url%></li>
        <li><%= link_to'blog', blog_url%></li>
        <li><%= link_to'contact', contact_url%></li>



      </ul>

    </ul>

    </div>
    </div>
    </div>

    </header>

portfolio/app/views/layouts/application.html.erb
  <!doctype html>
 <html>
  <head>
    <title>Portfolio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">
     




  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->


</head>
<body>
<%= render 'layouts/header'%>

<%= yield %>
<%= javascript_include_tag 'application' %>

<style><%= yield :stylesheets %></style>


  


    <!-- Navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

<a class="navbar-brand" href="home">Medina-Virginie</a>
        </div>
        <div class="navbar-collapse collapse">
<ul class="nav navbar-nav navbar-right">


      <ul>
        <li><%= link_to'home', root_url%></li>
        <li><%= link_to'portfolio', portfolio_url%></li>
        <li><%= link_to'blog', blog_url%></li>
        <li><%= link_to'contact', contact_url%></li>



      </ul>

    </ul>

    </div>
    </div>
    </div>

    </header>

<footer>

<hr class="small">
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/virginie.medina.9 "><i class="fa fa-facebook-square" aria-hidden="true"></i>

                        </li>
                        <li>
                            <a href="https://twitter.com/MedinaMedinini?lang=fr"><i class="fa fa-twitter" aria-hidden="true"></i>


                        </li>
                        <li>
                            <a href="https://github.com/virginie33 "><i class="fa fa-github"></i>

                        </li>
                    </ul>

                    <p class="text-muted">Copyright &copy; medinavirginie 2016</p>
                </a>
            

                </div>
            </div>
        </div>
   

</footer>
    






<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="js/bootstrap.min.js"></script>
 






  <javascript src="http://jquery.com/jquery.js">
  <javascript src="//jquery.com/jquery.js">

</body>
</html>

portfolio/app/views/pages/blog.html.erb
<!-- A Propos -->
            
              <div id=" APropos">
                  <div class="container">
                    <div class="row">
                      <h3>Un peu de lecture ?</h3>
                        
             <div class="section">
       </div>

</div>
</div>
</div>




           <div class="container Propos">
                <div class="row">
                <div class="col-lg-6">
               
        
                
        <br/>
          <div class="col-md-4 wow fadeInRight animated ">
                 
                    <strong class="about_us_p">Je m’appelle Virginie-Medina, j'ai 37 ans et je suis en reconversion  .</p>
                </div>
                <div class="col-md-4  wow fadeInRight animated">
                    <p class="about_us_p"> développeuse junior soit back-end (Ruby, Ruby on rails), ou front-end,Je viens de finir la formation simplon.co , école du numérique en FOAD,J'ai aussi suivis les cours openclassroom  .</strong>
                </div>
            </div>
        </div>
    </p>
    </div>
 
   
    </div>

   </section>


<hr></hr>

     <div class="container">
            <div class="row">
              <h3>mes progressions!</h3>


                <div class="col-md-4  wow fadeInLeft animated">
                    <div class="single_progress_bar">
                        <h5>HTML/CSS</h5>
            <div class="progress">
            <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="60" style="width: 60%">
            <span class="sr-only"></span>
        </div>
          </div>
            <br/>
              <h5>BootStrap</h5>
              <div class="progress">
              <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="50" style="width: 50%">
              <span class="sr-only"></span>
              </div>
                </div>
                  <br/>
              <h5>JavaScript</h5>
                <div class="progress">
                <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="10" style="width: 10%">
                <span class="sr-only"></span>
            </div>
        </div>
      <br/>
            <h5>Wordpress</h5>
            <div class="progress">
            <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="55" style="width: 55%">
            <span class="sr-only"></span>
          </div>
      </div>
    <br/>
        <h5>Ruby et Ruby on rails </h5>
        <div class="progress">
        <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="55" style="width: 55%">
        <span class="sr-only"></span>
           </div>
        </div>
     </div>
  </div>


                                             </div>
                                            </div>
                                         </div>
                                       </div>
                                     </div>
                                   </div>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>
               

portfolio/app/views/pages/contact.html.erb
    <!-- Map -->
   <section id="contact" class="map">
        <iframe width="100%" height="200%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d45411.74380037778!2d-1.283914252888475!3d44.653570857689104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5361aa5a46a1d3%3A0x1c06651a91b0a4b0!2s33970+L%C3%A8ge-Cap-Ferret!5e0!3m2!1sfr!2sfr!4v1462737811837" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>  </iframe>
        <br />
        <small>
            <a href="ttps://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d45411.74380037778!2d-1.283914252888475!3d44.653570857689104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5361aa5a46a1d3%3A0x1c06651a91b0a4b0!2s33970+L%C3%A8ge-Cap-Ferret!5e0!3m2!1sfr!2sfr!4v1462737811837  "></a>
        </small>
        </iframe>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Adresse</strong>
                    </h4>
                    <p>1 av des pins<br>Lége cap ferret</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i>05/57/18/48/83</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i>medinini@hotmail.fr</li>
                        </ul>
                        </div>
                      </div>
                  </div>



             </footer>
<hr></hr>
<center>
<form action="mailto:medinini@hotmail.fr" method="post" name="contact">
  <p><label for="user">Nom :</label>
  <input type="text" id="user" value="" /></p>

  <p><label for="emailaddress">Email :</label>
  <input type="text" id="emailaddress" value="" /></p>

  <p><label for="comments">Message :</label>
  <textarea id="comments" rows="5" cols="25"></textarea></p>



  <p><div style="margin-left: 150px;">
    <input type="submit" value="Envoyer" />
    <input type="reset" value="Reset" />
  </div></p>
</center>
</form>

portfolio/app/views/pages/home.html.erb
 <section class="services" id="SERVICE">
        <div class="container">
            <div class="row">
                <div class="col-md-3 text-center">
                    <div class="single_service wow fadeInUp" data-wow-delay="1s">
                        
                        <h2>Madevise</h2>
                        <strong>et d'en apprendre tous les jours,pour m'amélioré.</strong>
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="single_service wow fadeInUp" data-wow-delay="2s">
                        
                        <h2>passion</h2>
                        <strong>dans le web ainsi que toutes les nouvelles technologie</strong>
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="single_service wow fadeInUp" data-wow-delay="3s">
                       
                        <h2>Loisirs</h2>
                        <strong>Lecture, informatique (programation).</strong>
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="single_service wow fadeInUp" data-wow-delay="4s">
                       
                        <h2>Formation</h2>
                        <strong>formation simplon.co et suivi de cour openclassroom (école du numérique).</strong>
                    </div>
                </div>
            </div>
        </div>
  </section>

        <!-- Compétences -->
                  <div id="Competences" class="text-center">
                            <div class="container">
                 <div class="section-title center">
                     <h2>Un aperçu de mes compétences</h2>
                    <div class="line">

             </div>
         </div>
            <div class="space"></div>
           <div class="row">
           <div class="col-md-3 col-sm-6 service">

          <h4>Mes compétences.</h4>
          <strong>html5.</strong>
          <strong>css3.</strong>
          <strong>Bootstrap.</strong>
          <strong>javascript.</strong>
          <strong>ruby.</strong>
          <strong>ruby on rails.</strong>
  </div>
     <div class="col-md-3 col-sm-6 service">

    <h4>Certificat</h4>
    <li><a href="http://openclassrooms.com/course-certificates/77280543"> comprendre le web</a></li>
           <li><a href="http://openclassrooms.com/course-certificates/19434168"> Apprenez a creer votre site web avec HTML5 et CSS3</a></li>
           <li><a href="http://openclassrooms.com/course-certificates/55593109">Prenez en main Bootstrap</a></li>
           <li> <a href="http://openclassrooms.com/course-certificates/96526761"> Apprenez a naviguer en securite sur Internet</a></li>
           <li><a href="http://openclassrooms.com/course-certificates/91738989"> Concevez votre site web avec PHP et MySQL</a></li>
           <li><a href="https://openclassrooms.com/course-certificates/48045678">Gerer son code avec Git et GitHub</a></p>
           <li><a href="https://openclassrooms.com/course-certificates/13307682">Lancez-vous dans la programmation avec Ruby</a></li>
           <li><a href="https://openclassrooms.com/learning-path-certificates/2425368676 ">Integrateur Web</a></li>
   </div>
   <div class="col-md-3 col-sm-6 service">

       <h4>Mes badges code academy</h4>
      <li> <a href="https://www.codecademy.com/fr/users/teraPlayer35995/achievements">mes badges</a></li>
      <li><a href="http://github.com/virginie33">GITHUB</a></li>

 </div>
      <div class="col-md-3 col-sm-6 service">

     <h4>Mes sites en ligne</h4>
                 <li><a href="http://couleursvocales.comlu.com/  ">Couleurs vocales </a></li>
                 <li><a href="http://virginie33.github.io/defis-site">Défis site </a></li>
                  <li><a href="http://virginie33.github.io/cvvivi">CV</a></li>

</div>
          </div>
         </div>
        </div>

portfolio/app/views/pages/portfolio.html.erb
 

   <h4><center>Ma gallerie</center></h4>
<div class="container">
  <div class="row">
      <h4>centre formation simplon.co</h4>
    <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag '3.png'%>   </div>
          <h4>ruby jeux combat</h4>
        <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag '5.png'%></div>
           <h4>bootstrap</h4>
        <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag 'bootstrap.jpg'%>   </div>
         <h4>defis simplon : front end</h4>
        <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag 'defis.png' %>  </div>
           <h4>demo cv : meteor</h4>
      <div class="col-md-3 col-sm-4 col-xs-6"> <%= image_tag 'cv.png' %>  </div>
        <h4>jeux ;js :coockies clikers </h4>
        <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag '2.png' %>  </div>
       <h4>site pour une asso : couleursvocales</h4>
      <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag 'couleursvocales.png' %>  </div>
        <h4>Github </h4>
        <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag '4.png' %>   </div>
        <h4>obsidian : Ruby on rails </h4>
       <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag 'obsidian.png'%>   </div>
       <h4>cv : html css </h4>
       <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag '1.png'%>   </div>
        <h4>portfolio ruby on rails </h4>
       <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag 'port.png'%>   </div>

      <h4>cv bootstrap </h4>
       <div class="col-md-3 col-sm-4 col-xs-6"><%= image_tag 'curry.png'%>   </div>
</div>
</div>